# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDE_app', '0002_auto_20221217_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
