# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDE_app', '0003_auto_20221217_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('k_id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
