# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDE_app', '0004_files_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('k_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
