# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-17 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDE_app', '0005_auto_20221217_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key',
            new_name='Keys',
        ),
    ]
