# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-19 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDE_app', '0006_auto_20221217_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('chunks', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='keys',
            name='nonce',
            field=models.BinaryField(),
        ),
    ]
