# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-12-19 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDE_app', '0007_auto_20221219_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Files',
        ),
    ]
